# Generated by Django 4.2 on 2023-04-29 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(db_index=True, max_length=256)),
                ('handle', models.TextField()),
                ('display_name', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('indexed_at', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField()),
                ('from_actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='stats.actor')),
                ('to_actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='stats.actor')),
            ],
        ),
    ]
