# Generated by Django 4.2 on 2023-05-07 16:05

from django.db import migrations, models
import django.utils.timezone
from django.db.models import F
from django.db.models.functions import Coalesce


def migrate_indexed_at(apps, schema_editor):
    Actor = apps.get_model("stats", "Actor")
    db_alias = schema_editor.connection.alias
    Actor.objects.using(db_alias).update(
        created_at=Coalesce(F("indexed_at"), F("created_at"))
    )


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0002_actor_created_at_actor_updated_at'),
    ]

    operations = [
        migrations.RunPython(migrate_indexed_at),
        migrations.RemoveField(
            model_name='actor',
            name='indexed_at',
        ),
        migrations.AlterField(
            model_name='actor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
