apiVersion: apps/v1
kind: Deployment
metadata:
  name: bsky-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bsky
      component: crawler
  template:
    metadata:
      labels:
        app: bsky
        component: crawler
    spec:
      containers:
        - name: crawler
          image: ealmuina/bsky:latest
          envFrom:
            - secretRef:
                name: bsky-secrets
          command: [ "python", "-u", "-m", "stats.crawler" ]
          volumeMounts:
            - mountPath: /app/db
              name: sqlite-volume
      volumes:
        - name: sqlite-volume
          persistentVolumeClaim:
            claimName: bsky-sqlite-pvc
